#pragma once
#define DPAD_UP 1
#define DPAD_RIGHT 2
#define DPAD_UPRIGHT 3
#define DPAD_DOWN 4
#define DPAD_DOWNRIGHT 6
#define DPAD_LEFT 8
#define DPAD_UPLEFT 9
#define DPAD_DOWNLEFT 12

#define GAMEPAD_BUTTON_A 0
#define GAMEPAD_BUTTON_B 5
#define GAMEPAD_BUTTON_X 7
#define GAMEPAD_BUTTON_Y 10
#define GAMEPAD_BUTTON_CROSS GAMEPAD_BUTTON_A
#define GAMEPAD_BUTTON_CIRCLE GAMEPAD_BUTTON_B
#define GAMEPAD_BUTTON_SQUARE GAMEPAD_BUTTON_X
#define GAMEPAD_BUTTON_TRIANGLE GAMEPAD_BUTTON_Y

#define GAMEPAD_BUTTON_BUMPL 11
#define GAMEPAD_BUTTON_TRIGL 13
#define GAMEPAD_BUTTON_BUMPR 14
#define GAMEPAD_BUTTON_TRIGR 15

