#define GLFW_INCLUDE_VULKAN
#define VK_USE_PLATFORM_WIN32_KHR 

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_ENABLE_EXPERIMENTAL

#define STB_IMAGE_IMPLEMENTATION

#define TINYOBJLOADER_IMPLEMENTATION
#include "pch.h"
